Import libraries and load dataset

In [2]:
import numpy as np
import pandas as pd

df = pd.read_csv("Titanic-Dataset.csv")

print("Dataset loaded successfully!")
print("Dataset shape:", df.shape)
df.head()

Dataset loaded successfully!
Dataset shape: (891, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
marks = np.array([70, 80, 90, 60, 100])

print("Marks:", marks)
print("Total:", np.sum(marks))
print("Average:", np.mean(marks))
print("Highest:", np.max(marks))

Marks: [ 70  80  90  60 100]
Total: 400
Average: 80.0
Highest: 100

In [4]:
print("First five rows:")
display(df.head())

print("Last five rows:")
display(df.tail())

print("Dataset shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nDataset information:")
df.info()

First five rows:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Last five rows:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

Dataset shape: (891, 12)

Columns:
['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 118.9 KB

In [5]:
display(df.describe())

print("Missing values in each column:")
display(df.isnull().sum())

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

Missing values in each column:

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [6]:
print("Selected passenger details:")
display(df.loc[:, ["Name", "Sex", "Age", "Survived"]].head(10))

print("First five rows and first four columns:")
display(df.iloc[0:5, 0:4])

Selected passenger details:

                                                Name     Sex   Age  Survived
0                            Braund, Mr. Owen Harris    male  22.0         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0         1
2                             Heikkinen, Miss. Laina  female  26.0         1
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0         1
4                           Allen, Mr. William Henry    male  35.0         0
5                                   Moran, Mr. James    male   NaN         0
6                            McCarthy, Mr. Timothy J    male  54.0         0
7                     Palsson, Master. Gosta Leonard    male   2.0         0
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0         1
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0         1

First five rows and first four columns:

,PassengerId,Survived,Pclass,Name
0,1,0,3,"Braund, Mr. Owen Harris"
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th..."
2,3,1,3,"Heikkinen, Miss. Laina"
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)"
4,5,0,3,"Allen, Mr. William Henry"

Question 1:

In [7]:
# Question 1:
# How many female passengers in 2nd Class survived?

q1 = df.loc[
    (df["Sex"] == "female") &
    (df["Pclass"] == 2) &
    (df["Survived"] == 1)
]

print("Female passengers in 2nd Class who survived:", len(q1))
display(q1[["Name", "Age", "Pclass", "Survived"]])

Female passengers in 2nd Class who survived: 70

                                                  Name   Age  Pclass  Survived
9                  Nasser, Mrs. Nicholas (Adele Achem)  14.0       2         1
15                    Hewlett, Mrs. (Mary D Kingcome)   55.0       2         1
43            Laroche, Miss. Simonne Marie Anne Andree   3.0       2         1
53   Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...  29.0       2         1
56                                   Rugg, Miss. Emily  21.0       2         1
..                                                 ...   ...     ...       ...
801        Collyer, Mrs. Harvey (Charlotte Annie Tate)  31.0       2         1
865                           Bystrom, Mrs. (Karolina)  42.0       2         1
866                       Duran y More, Miss. Asuncion  27.0       2         1
874              Abelson, Mrs. Samuel (Hannah Wizosky)  28.0       2         1
880       Shelley, Mrs. William (Imanita Parrish Hall)  25.0       2         1

[70 rows x 4 columns]

Question 2:

In [8]:
# Question 2:
# How many passengers younger than 12 survived?
# What were their passenger classes?

q2 = df.loc[
    (df["Age"] < 12) &
    (df["Survived"] == 1)
]

print("Passengers under 12 who survived:", len(q2))

print("\nSurvivors by passenger class:")
display(q2["Pclass"].value_counts().sort_index())

Passengers under 12 who survived: 39

Survivors by passenger class:

Pclass
1     3
2    17
3    19
Name: count, dtype: int64

Findings

In [9]:
print("FINDINGS")
print("-" * 40)

print(
    f"1. Female passengers in 2nd Class who survived: {len(q1)}"
)

print(
    f"2. Passengers younger than 12 who survived: {len(q2)}"
)

print("\nClass-wise counts for surviving passengers under 12:")
print(q2["Pclass"].value_counts().sort_index().to_string())

print("\nConclusion:")
print(
    "These queries helped me practise filtering rows with multiple "
    "conditions, counting records, selecting columns, and grouping results."
)

FINDINGS
----------------------------------------
1. Female passengers in 2nd Class who survived: 70
2. Passengers younger than 12 who survived: 39

Class-wise counts for surviving passengers under 12:
Pclass
1     3
2    17
3    19

Conclusion:
These queries helped me practise filtering rows with multiple conditions, counting records, selecting columns, and grouping results.